# Generated by Django 4.1.2 on 2022-10-25 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asteroïd', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
